[versions]
application = "8.2.2"
kotlin = "1.9.0"
hilt = "2.49"
ksp = "1.9.22-1.0.17"
google-services = "4.4.2"
crashlytics = "3.0.2"
android-core = "1.13.1"
android-splash = "1.0.1"
android-appcompat = "1.6.1"

lifecycle = "2.5.1"
lifecycleprocess = "2.8.3"
compose = "2023.08.00"
navigation = "2.7.7"
constraintlayout = "1.0.1"
activity = "1.9.0"
browser = "1.8.0"
charty = "2.0.0-alpha01"
coroutines = "1.7.3"
timber = "5.0.1"
retrofit2 = "2.9.0"
okhttp3 = "4.9.3"
firebase = "33.2.0"
firbasektx ="22.1.0"
fragmentktx ="1.6.1"
work = "2.9.0"
moshi = "1.15.1"
room = "2.6.1"
hiltKtx = "1.2.0"
coil = "2.7.0"
lottie = "6.3.0"
datastore = "1.1.1"
junit = "4.13.2"
mockk = "1.13.9"
coroutines-test = "1.7.3"
junit-ext = "1.1.5"
test-runner = "1.5.2"
espresso = "3.5.1"
appcompat = "1.7.0"
material = "1.11.0"
materialcompose = "1.6.0"
uiTooling = "1.7.2"
foundationLayoutAndroid = "1.6.8"
constraintlayoutVersion = "2.1.4"
navigationFragmentKtx = "2.8.3"
navigationUiKtx = "2.8.3"

google-client ="1.38.1"
google-api-client ="1.32.1"
google-ad ="23.3.0"
google-auth ="21.2.0"
google-auth-jetty ="1.23.0"
google-api-youtube ="v3-rev222-1.25.0"

google-api-client-android ="1.23.1"

google-oss ="17.0.0"

google-accompanist-drawable ="0.36.0"
google-accompanist-systemuicontroller ="0.30.0"

google-media3 ="1.2.1"
ktlint = "12.1.1"
androidxConstraintlayout = "2.2.0"
[plugins]
android-application = { id = "com.android.application", version.ref = "application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
android-library = { id = "com.android.library", version.ref = "application" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "android-splash" }
appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }


# Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleprocess" }
# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class" }
compose-material = { module = "androidx.compose.material:material" , version.ref = "materialcompose"}


navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation"}
#constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout"}
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity"}
browser = { module = "androidx.browser:browser", version.ref = "browser"}
charty = { module = "com.himanshoe:charty", version.ref = "charty"}

# Coroutine
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines"}

# Network
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2"}
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2"}
retrofit2-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2"}
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp3"}
okhttp = { module = "com.squareup.okhttp3:okhttp"}
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor"}

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase"}
firebase-analytics = { module = "com.google.firebase:firebase-analytics"}
firebase-messaging = { module = "com.google.firebase:firebase-messaging"}
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics"}
firebase-config = { module = "com.google.firebase:firebase-config"}
firebase-crashlytics-buildtools = { module = "com.google.firebase:firebase-crashlytics-buildtools", version.ref = "crashlytics"}
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firbasektx"}
firebase-auth = { module = "com.google.firebase:firebase-auth"}
firebase-storage = { module = "com.google.firebase:firebase-storage"}

# Work
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work"}

# Moshi
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi"}
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi"}

# Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room"}
room = { module = "androidx.room:room-ktx", version.ref = "room"}

# Dependency Management
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltKtx"}
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltKtx"}
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltKtx"}

# Image
coil = { module = "io.coil-kt:coil", version.ref = "coil"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil"}
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie"}

# Data Store
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore"}
#framework
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentktx"}
#google api
google-http-client-android = { module = "com.google.http-client:google-http-client-android", version.ref = "google-client"}
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "google-api-client-android"}
google-api-client-gson = { module = "com.google.api-client:google-api-client-gson", version.ref = "google-api-client"}
google-api-service-youtube = { module = "com.google.apis:google-api-services-youtube", version.ref = "google-api-youtube"}
google-oauth-client-jetty = { module = "com.google.oauth-client:google-oauth-client-jetty", version.ref = "google-auth-jetty"}
google-accompanist-drawablepainter= { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "google-accompanist-drawable"}
google-accompanist-systemuicontroller= { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist-systemuicontroller"}


#admob
google-play-service-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "google-ad"}
google-play-service-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-auth"}

#license
google-play-service-oss = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "google-oss"}

#exo-player
google-media3-common = { module = "androidx.media3:media3-common", version.ref = "google-media3"}
google-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "google-media3"}
google-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "google-media3"}
google-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "google-media3"}
google-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "google-media3"}
google-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "google-media3"}


# Unit Test
junit = { module = "junit:junit", version.ref = "junit"}
mockk = { module = "io.mockk:mockk", version.ref = "mockk"}
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test"}


# Android Test
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext"}
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso"}
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk"}
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4"}
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest"}
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayoutVersion" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
hilt-android-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt"}
hilt-google-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt"}

test-runner = { module = "androidx.test:runner", version.ref = "test-runner"}
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }